name: Publish Website
on:
  push:
    branches:
      - 'main'
      
  pull_request:
    branches:
      - 'main'
          
                                                   
jobs:
   build:
    runs-on: ubuntu-latest
    steps:  
  
     - uses: actions/checkout@v3
       with:
        fetch-depth: 0
        
     - name: Generate semver
       id: version-generator
       run: |
        export ARTEFACT_VERSION=$(git describe --long --always)
        echo ::set-output name=ARTEFACT_VERSION::$ARTEFACT_VERSION 
       
         
     - name: Build Docker image
       run: docker build . --tag mastermole/my_website:${{ steps.version-generator.outputs.ARTEFACT_VERSION }}
    
     - name: Login to DockerHub
       uses: docker/login-action@v1 
       with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    
     - name: Push to the DockerHub
       run: docker push mastermole/my_website:${{ steps.version-generator.outputs.ARTEFACT_VERSION }}
       
           
     - name: Docker pull and run from Docker Hub
       uses: appleboy/ssh-action@master
       with:
             host : ${{ secrets.HOSTNAME  }}
             username : ${{ secrets.USER_NAME  }}
             key: ${{ secrets.AWS_PRIVATE_KEY }}
             port: ${{ secrets.PORT }}
             script: |
               docker pull mastermole/my_website:${{ steps.version-generator.outputs.ARTEFACT_VERSION }}
               docker stop website
               docker rm website
               docker run -d -p 80:80 --name website mastermole/my_website:${{ steps.version-generator.outputs.ARTEFACT_VERSION }}  
                             
           
                           
         
            
            
     
            
     
            
            
            
            
            
            
            
            
